contacts/urls.py
from django.urls import path, include
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('add_contact/', views.add_contact, name='add_contact'),
    path('edit_contact/<int:pk>/', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:pk>/', views.delete_contact, name='delete_contact'),
    path('upcoming_birthdays_list/', views.upcoming_birthdays_list, name='upcoming_birthdays_list'),
]

files/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
    path('delete/<str:file_id>/', views.delete_file, name='delete_file')
]

interactive_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("helper.urls")),
    path("files/", include("files.urls")),
    path("users/", include("users.urls")),
    path('contacts/', include("contacts.urls")),
    path('notes/', include("notes.urls"))
]

contacts/models.py
# contacts/models.py
import re
from django.db import models
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.utils import timezone
from datetime import timedelta


def validate_phone_number(value):
    phone_regex = r'^\+?1?\d{9,15}$'
    if not re.match(phone_regex, value):
        raise ValidationError('Invalid phone number format.')

class Contact(models.Model):
    fullname     = models.CharField(max_length=100)
    address      = models.TextField(blank=True)
    phone_number = models.CharField(max_length=20,blank=True, validators=[validate_phone_number])
    email        = models.EmailField(blank=True, validators=[validate_email])
    born_date    = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.fullname if self.fullname else "Unnamed Contact"

    @staticmethod
    def upcoming_birthdays(days):
        today = timezone.now()
        future_date = today + timedelta(days=days)
        return Contact.objects.filter(
            born_date__day   = future_date.day,
            born_date__month = future_date.month
        )
    @staticmethod
    def search_contacts(query):
        return Contact.objects.filter(name__icontains=query)
    

contacts/forms.py
from django.forms import DateField, DateInput, HiddenInput, IntegerField, EmailInput, EmailField, ModelForm, CharField, TextInput
from .models import Contact
from django import forms
from datetime import date


class ContactForm(ModelForm):
    id           = IntegerField(widget=HiddenInput(), required=False)
    fullname     = CharField(required=True, min_length=3, max_length=225, widget=TextInput(attrs={"class": "form-control"}))
    email        = EmailField(required=True, min_length=8, max_length=225, widget=EmailInput(attrs={"class": "form-control"}))
    phone_number = CharField(required=True, max_length=15, widget=TextInput(attrs={"class": "form-control"}))
    born_date    = DateField(required=True, widget=DateInput(attrs={"type": "date", "class": "form-control"}))
    address      = CharField(required=True, max_length=225, widget=TextInput(attrs={"class": "form-control"}))

    class Meta:
        model  = Contact
        fields = ['fullname', 'email', 'phone_number', 'born_date', 'address']
        widgets = {
            'born_date': forms.DateInput(attrs={'type': 'date'}),
        }

contacts/views.py
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from datetime import timedelta
from .forms import ContactForm
from .models import Contact
from datetime import date, timedelta

# Create your views here.
@login_required
def contact_list(request):
    query = request.GET.get('query')

    if query:
        contacts = Contact.objects.filter(fullname__icontains=query)
    else:
        contacts = Contact.objects.all()

    return render(request, 'contacts/contact_list.html', {'contacts': contacts})

@login_required
def add_contact(request):
    contact_form = ContactForm(instance=Contact())
    if request.method == "POST":
        contact_form = ContactForm(request.POST, instance=Contact())
        if contact_form.is_valid():
            contact_form.save()
            fullname = contact_form.cleaned_data['fullname']
            messages.success(request, f'You have successfully added {fullname}')
            return redirect('contacts:contact_list')
        else:
            messages.error(request, "Error")
    return render(request, 'contacts/add_contact.html', {'form_contact': contact_form})


@login_required
def edit_contact(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == "POST":
        contact_form = ContactForm(request.POST, instance=contact)
        if contact_form.is_valid():
            contact = contact_form.save()
            return redirect('contacts:contact_list')
    else:
        contact_form = ContactForm(instance=contact)
    return render(request, 'contacts/edit_contact.html', context={'form': contact_form})


@login_required
def delete_contact(request, pk):
    contact = get_object_or_404(Contact, pk=pk)
    if request.method == "POST":
        contact.delete()
        messages.success(request, f'Contact {contact.fullname} has been deleted.')
        return redirect('contacts:contact_list')
    return render(request, 'contacts/delete_contact.html', {'contact': contact})


def upcoming_birthdays_list(request):
    days = request.GET.get('days')
    try:
        days = int(days)
    except (TypeError, ValueError):
        days = 365  # За замовчуванням шукаємо на наступні 365 днів

    # Отримуємо всі контакти з бази даних
    contacts = Contact.objects.all()

    # Отримуємо сьогоднішню дату
    today = date.today()

    # Визначаємо цільну дату для пошуку
    target_date = today + timedelta(days=days)

    # Ініціалізуємо порожній список для майбутніх днів народження з даними контактів
    upcoming_birthdays = []

    # Збираємо всі майбутні дні народження з даними контактів
    for contact in contacts:
        if contact.born_date:
            # Визначаємо дату народження для поточного року
            birthday_this_year = date(today.year, contact.born_date.month, contact.born_date.day)

            # Перевіряємо, чи дата народження цього року ще не минула і входить в потрібний період
            if today <= birthday_this_year <= target_date:
                upcoming_birthdays.append({
                    'contact': contact,
                    'birthday_date': birthday_this_year,
                })

    # Сортуємо список за датами народжень
    upcoming_birthdays.sort(key=lambda x: x['birthday_date'])

    return render(request, 'contacts/upcoming_birthdays_list.html', {
        'upcoming_birthdays': upcoming_birthdays,
        'days': days,
        'target_date': target_date,
    })

contacts/templates/contacts/add_contact.html
{% extends 'helper/base.html' %}

{% block content %}

<div class="container">
  <div class="row">
    <div class="col-md-8 offset-md-2">
      <form action="{% url 'contacts:add_contact' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <h1>Додати контакт</h1>

        <div class="mb-3">
          <label for="id_fullname" class="form-label">Ім'я</label>
          {{ form_contact.fullname }}
          <span class="text-danger">{{ form_contact.errors.fullname }}</span>
        </div>

        <div class="mb-3">
          <label for="id_email" class="form-label">Пошта</label>
          {{ form_contact.email }}
          <span class="text-danger">{{ form_contact.errors.email }}</span>
        </div>

        <div class="mb-3">
          <label for="id_phone_number" class="form-label">Номер телефону</label>
          {{ form_contact.phone_number }}
          <span class="text-danger">{{ form_contact.errors.phone_number }}</span>
        </div>

        <div class="mb-3">
          <label for="id_born_date" class="form-label">Дата народження</label>
          {{ form_contact.born_date }}
          <span class="text-danger">{{ form_contact.errors.born_date }}</span>
        </div>

        <div class="mb-3">
          <label for="id_address" class="form-label">Адреса</label>
          {{ form_contact.address }}
          <span class="text-danger">{{ form_contact.errors.address }}</span>
        </div>

        <button type="submit" class="btn btn-primary">Зберегти</button>
        <button type="reset" class="btn btn-secondary">Скинути</button>

      </form>
    </div>
  </div>
</div>

{% endblock %}

contacts/templates/contacts/contact_list.html
{% extends 'helper/base.html' %}

{% block content %}
<html>
<head>
    <title>Список контактів</title>
</head>
<body>
    <h1>Список контактів</h1>
    <a href="{% url 'contacts:add_contact' %}" class="btn btn-primary">Додати контакт</a>
    <!-- Додана кнопка для переходу на сторінку з майбутніми днями народження -->
    <a href="{% url 'contacts:upcoming_birthdays_list' %}" class="btn btn-primary">Майбутні дні народження</a>
    <br><br>

    <!-- Форма для пошуку контактів -->
    <form method="GET" action="{% url 'contacts:contact_list' %}">
        <div class="row g-3">
                  <div class="col-auto">
                      <input type="text" class="form-control" name="query" placeholder="Введіть ім'я для пошуку...">
                  </div>
                  <div class="col-auto">
                    <button type="submit" class="btn btn-secondary mb-3">Знайти</button>
                  </div>
        </div>

    </form>


    {% for contact in contacts %}
        <div class="card mb-3">
            <div class="card-body">
                <strong>ПІБ:</strong> {{ contact.fullname }}<br>
                <strong>Email:</strong> {{ contact.email }}<br>
                <strong>Телефон:</strong> {{ contact.phone_number }}<br>
                <strong>Дата народження:</strong> {{ contact.born_date|date:"d.m.Y" }}<br>
                <!-- Додайте інші поля, які хочете відобразити -->
                <a href="{% url 'contacts:edit_contact' contact.pk %}" class="btn btn-warning mt-3">Змінити</a>
                <a href="{% url 'contacts:delete_contact' contact.pk %}" class="btn btn-danger mt-3">Видалити</a>
            </div>
        </div>
    {% empty %}
        <p>Немає контактів для відображення.</p>
    {% endfor %}


    <h2>Пошук по даті народження</h2>
    <form method="GET" action="{% url 'contacts:contact_list' %}">
        {{ form.as_p }}
        <div class="row g-3">
                <div class="col-auto">
                    <input type="text" class="form-control" id="days" name="days" value="{{ days }}" min="1" max="365" placeholder="Введіть кількість днів для пошуку...">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-secondary">Пошук</button>
                </div>
        </div>
    </form>
    
</body>
</html>
{% endblock %}

contacts/templates/contacts/delete_contact.html
{% extends 'helper/base.html' %}

{% block content %}

<div class="d-flex justify-content-between align-items-center mb-3">
    <h2>Видалити контакт</h2>
    <a href="{% url 'contacts:contact_list' %}" class="btn btn-danger btn-sm">Назад</a>
</div>

<p>Ви впевнені, що хочете видалити контакт: {{ contact.fullname }}?</p>

<form method="post" action="{% url 'contacts:delete_contact' contact.pk %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-danger btn-sm">Видалити</button>
</form>

{% endblock %}

contacts/templates/contacts/edit_contact.html
{% extends 'helper/base.html' %}

{% block content %}

<head>
    <title>Змінити контакт</title>
</head>
<body>
    <h1>{% if form.instance.pk %}Змінити контакт{% else %}Новий контакт{% endif %}</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Зберегти</button>
    </form>
</body>
</html>
{% endblock %}

contacts/templates/contacts/search_result.html
{% extends 'helper/base.html' %}

{% block content %}

<html>
<head>
    <title>Пошук по даті народження</title>
</head>
<body>
    <h2>Результат вашого пошуку</h2>
    <a href="{% url 'contacts:contact_list' %}" class="btn btn-danger btn-sm">Назад</a>
    <ul>
        {% for contact in contacts %}
            <li>{{ contact.fullname }} - {{ contact.born_date }}</li>
        {% empty %}
            <li>Контактів не знайдено</li>
        {% endfor %}
    </ul>
</body>
</html>

{% endblock %}

contacts/templates/contacts/upcoming_birthdays_list.html
{% extends 'helper/base.html' %}

{% block content %}
<html>
<head>
    <title>Контакти з майбутніми днями народження</title>
</head>
<body>
    <h1>Контакти з майбутніми днями народження</h1>

    <h2>Вкажіть кількість днів до дня народження</h2>
    <form method="GET" action="{% url 'contacts:upcoming_birthdays_list' %}">
        <input type="number" id="days" name="days" value="{{ days }}" min="1" max="365" placeholder="Введіть кількість днів для пошуку...">
        <button type="submit" class="btn btn-secondary">Показати</button>
    </form>
    
    <hr>

    {% if upcoming_birthdays %}
        <h3>Контакти з майбутніми днями народження до {{ target_date|date:"d.m.Y" }}</h3>
        

            {% for item in upcoming_birthdays %}
                <div class="card mb-3">
                    <div class="card-body">
                        {{ item.contact.fullname }} - Дата народження: {{ item.birthday_date|date:"d.m.Y" }}
                        - <a href="{% url 'contacts:edit_contact' item.contact.pk %}" class="btn btn-warning">Змінити</a>
                        - <a href="{% url 'contacts:delete_contact' item.contact.pk %}" class="btn btn-danger">Видалити</a>
                        </div>
                </div>
            {% endfor %}
    {% else %}
        <h3>Немає контактів з майбутніми днями народження до {{ target_date|date:"d.m.Y" }}</h3>
    {% endif %}
    
</body>
</html>
{% endblock %}