files/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
    path('delete/<str:file_id>/', views.delete_file, name='delete_file')
]

interactive_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("helper.urls")),
    path("files/", include("files.urls")),
    path("users/", include("users.urls")),
    path('contacts/', include("contacts.urls")),
    path('notes/', include("notes.urls"))
]

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.main, name='index'),
    path('add_notes/', views.note, name='add_notes'),
    path('tag/', views.tag, name='tag'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('edit_note/<int:pk>/', views.edit_note, name='edit'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('tag/<int:tag_id>/delete/', views.delete_tag, name='delete_tag'),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=25, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='tag of username')
        ]

    def __str__(self):
        return f"{self.name}"


class Note(models.Model):
    name = models.CharField(max_length=50, null=False, unique=True)
    description = models.CharField(max_length=150, null=False)
    done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField(Tag)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'name'], name='note of username')
        ]

    def __str__(self):
        return f"{self.name}"

notes/forms.py
from django.forms import ModelForm, CharField, TextInput, Textarea
from .models import Tag, Note


class TagForm(ModelForm):
    name = CharField(min_length=3, max_length=25, required=True, widget=TextInput())

    class Meta:
        model = Tag
        fields = ['name']


class NoteForm(ModelForm):

    name = CharField(min_length=3, max_length=50, required=True, widget=TextInput())
    description = CharField(min_length=5, max_length=150, required=True, widget=Textarea())

    class Meta:
        model = Note
        fields = ['name', 'description']
        exclude = ['tags']

notes/views.py
import django.db.utils
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.db import IntegrityError
from django.contrib import messages

from .forms import TagForm, NoteForm

from .models import Tag, Note


@login_required
def main(request):
    query = request.GET.get('q')
    tag_query = request.GET.get('tag')
    if request.user.is_authenticated:
        if query:
            notes = Note.objects.filter(
                Q(name__icontains=query) | Q(description__icontains=query),
                user=request.user
            ).distinct()
        elif tag_query:
            notes = Note.objects.filter(
                tags__name__icontains=tag_query,
                user=request.user
            ).distinct()
        else:
            notes = Note.objects.filter(user=request.user)
    else:
        notes = []
    return render(request, 'notes/index.html', {"notes": notes, "query": query, "tag_query": tag_query})


@login_required
def tag(request):
    tags = Tag.objects.filter(user=request.user).all()
    if request.method == 'POST':
        form = TagForm(request.POST)
        if form.is_valid():
            tag_name = form.cleaned_data['name']
            existing_tag = Tag.objects.filter(name=tag_name, user=request.user).first()
            if existing_tag:
                messages.error(request, f"Tag '{tag_name}' already exists.")
            else:
                tag = form.save(commit=False)
                tag.user = request.user
                try:
                    tag.save()
                    messages.success(request, f"Tag '{tag_name}' added successfully.")
                    return redirect('notes:tag')  # Redirect to the same page to clear the form
                except IntegrityError:
                    messages.error(request, "An error occurred while saving the tag.")
    else:
        form = TagForm()

    return render(request, 'notes/tag.html', {'form': form, 'tags': tags})

@login_required
def delete_tag(request, tag_id):
    tag = get_object_or_404(Tag, id=tag_id, user=request.user)
    tag.delete()
    messages.success(request, f"Tag '{tag.name}' deleted successfully.")
    return redirect('notes:tag')

@login_required
def note(request):
    tags = Tag.objects.filter(user=request.user).all()

    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            try:
                new_note = form.save(commit=False)
                new_note.user = request.user
                new_note.save()
            except django.db.utils.IntegrityError:
                messages.error(request, message="Заголовок має бути унікальним!")
                return redirect(to='notes:add_notes')
            choice_tags = Tag.objects.filter(name__in=request.POST.getlist('tags'), user=request.user)
            for tag in choice_tags.iterator():
                new_note.tags.add(tag)

            return redirect(to='notes:index')
        else:
            return render(request, 'notes/add_notes.html', {"tags": tags, 'form': form})

    return render(request, 'notes/add_notes.html', {"tags": tags, 'form': NoteForm()})


@login_required
def detail(request, note_id):
    note = get_object_or_404(Note, pk=note_id, user=request.user)
    return render(request, 'notes/detail.html', {"note": note})

@login_required
def set_done(request, note_id):
    Note.objects.filter(pk=note_id, user=request.user).update(done=True)
    return redirect(to='notes:index')


@login_required
def delete_note(request, note_id):
    Note.objects.get(pk=note_id, user=request.user).delete()
    return redirect(to='notes:index')


@login_required
def edit_note(request, pk):
    note = get_object_or_404(Note, pk=pk)
    if request.method == "POST":
        note_form = NoteForm(request.POST, instance=note)
        if note_form.is_valid():
            note = note_form.save()
            return redirect('notes:index')
    else:
        note_form = NoteForm(instance=note)
    return render(request, 'notes/edit_notes.html', context={'form': note_form})

notes/templates/notes/add_notes.html
{% extends "helper/base.html" %}

{% block content %}

<form method="POST" action="{% url 'notes:add_notes' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label class="form-label"> Заголовок:<br>
            {{ form.name }}
        </label>
        <span>{{ form.errors.name }}</span>
    </div>
    <div style="padding: 10px">
        <label class="form-label"> Текст нотатки:<br>
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Оберіть теги:<br>
            <select name="tags"  multiple="multiple" class="form-select">
                {% for tag in tags %}
                <option value="{{tag.name}}">{{tag.name}}</option>
                {% endfor %}
            </select>
        </label>
    </div>
    <div class="grid" style="padding: 10px">
        <button type="submit" class="btn btn-success">Зберегти</button>
        <button type="reset" class="btn btn-danger">Скинути</button>
    </div>
</form>
{% endblock %}

notes/templates/notes/detail.html
{% extends "helper/base.html" %} {% load extract_tags %} {% block content %}

<h1>{{note.name}}</h1>
<p>Description: <b>{{note.description}}</b></p>
<p>Time of creation: <kbd>{{note.created}}</kbd></p>
{% if note.done %}
<p>
  Status:
  <ins>Completed</ins>
</p>
{% else %}
<p>Status: <i>Not implemented</i></p>
{% endif %}
<p>Tags: <small> {{ note.tags|tags }} </small></p>
{% endblock %}

notes/templates/notes/edit_notes.html
{% extends 'helper/base.html' %}

{% block content %}

<head>
    <title>Змінити запис</title>
</head>
<body>
    <h1>{% if form.instance.pk %}Змінити запис{% else %}Новий запис{% endif %}</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success">Зберегти</button>
    </form>
</body>
</html>
{% endblock %}

notes/templates/notes/index.html
{% extends "helper/base.html" %}

{% block content %}
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 0px">
        <a href="{% url 'notes:add_notes' %}" role="button" class="btn btn-success mb-3">Додати нотатку</a></li>
        <a href="{% url 'notes:tag' %}" role="button" class="btn btn-success mb-3">Додати тег</a></li>
    </nav>

    <form method="GET" action="{% url 'notes:index' %}" style="margin-bottom: 20px;">
        <div class="row g-3">
                <div class="col-auto">
                    <input type="text" class="form-control" name="q" placeholder="Пошук нотаток...">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-success">Шукати</button>
                </div>
        </div>
    </form>

    <form method="GET" action="{% url 'notes:index' %}" style="margin-bottom: 20px;">
        <div class="row g-3">
                <div class="col-auto">
                    <input type="text" class="form-control" name="tag" placeholder="Пошук в тегах...">
                </div>
                <div class="col-auto">
                    <button type="submit" class="btn btn-success">Шукати</button>
                </div>
        </div>
    </form>

    {% if notes %}
        {% for note in notes %}
        <div class="card mb-3">
            <div class="card-body">
                {% if not note.done %}
                <a href="{% url 'notes:detail' note.id %}" role="button" class="outline"> <h2>{{ note.name }}</h2> </a>
                <a href="{% url 'notes:set_done' note.id %}" role="button" class="btn btn-primary"> Позначити як виконану </a>
                <a href="{% url 'notes:delete' note.id %}" role="button" class="btn btn-secondary"> Видалити нотатку </a>
                <a href="{% url 'notes:edit' note.id %}" role="button" class="btn btn-secondary"> Редагувати нотатку </a>
                {% else %}
                <a href="{% url 'notes:detail' note.id %}" role="button" class="secondary"><s>{{ note.name }}</s></a>
                <a href="{% url 'notes:delete' note.id %}" role="button" class="btn btn-secondary"> Видалити нотатку </a>
                {% endif %}
            </div>
        </div>
        {% endfor %}
    {% else %}
        <p>Нотаток не знайдено</p>
    {% endif %}
</main>
{% endblock %}

notes/templates/notes/tag.html
{% extends "helper/base.html" %}

{% block content %}
<main class="container">
    <h1>Додавання тегу</h1>
    <form method="POST" class="form-control">
        {% csrf_token %}
        {{ form.as_p }}
        {% if messages %}
        <ul class="messages" style="color: red">
            {% for message in messages %}
            <li class="{{ message.tags }}">{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        <button type="submit" class="btn btn-success">Додати тег</button>
    </form>
    <h2>Існуючі теги</h2>
    {% if tags %}

        {% for tag in tags %}
        <div class="card mb-3">
            <div class="card-body">
                <div class="row g-3">
                    <div class="col-auto">
                        {{ tag.name }}
                    </div>
                        <div class="col-auto ">
                        <a href="{% url 'notes:delete_tag' tag.id %}" class="btn btn-danger btn-sm" >Delete</a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}

    {% else %}
    <p>You have no tags yet.</p>
    {% endif %}
</main>
{% endblock %}