files/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
    path('delete/<str:file_id>/', views.delete_file, name='delete_file')
]

interactive_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("helper.urls")),
    path("files/", include("files.urls")),
    path("users/", include("users.urls")),
    path('contacts/', include("contacts.urls")),
    path('notes/', include("notes.urls"))
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .import views
from .forms import LoginForm, RegisterForm

app_name = 'users'

urlpatterns =[
    path('signup/', views.RegisterView.as_view(template_name='users/register.html', form_class=RegisterForm), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html', form_class=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset-password/complete/'),
            name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
    ]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):

    username = CharField(max_length=16,
                         min_length=3,
                         required=True,
                         widget=TextInput(attrs={"class": "form-control"}))

    email = EmailField(max_length=50,
                       required=True,
                       widget=EmailInput(attrs={"class": "form-control"}))

    password1 = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    password2 = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class LoginForm(AuthenticationForm):

    username = CharField(max_length=16,
                         min_length=3,
                         required=True,
                         widget=TextInput(attrs={"class": "form-control"}))

    password = CharField(required=True,
                          widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ['username', 'password']

users/views.py
from django.contrib.auth import logout
from django.contrib.auth.views import PasswordResetView
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.contrib import messages

from .forms import RegisterForm

# Create your views here.


class RegisterView(View):
    template_name = 'users/register.html'
    form_class = RegisterForm

    def get(self, request):
        return render(request, self.template_name, context={'form': self.form_class})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            messages.success(request, message=f'Hello {username}!. Your account register successfully!')
            return redirect(to='users:login')
        return render(request, self.template_name, context={'form': form})


class ResetPasswordView(SuccessMessageMixin, PasswordResetView):
    template_name = 'users/password_reset.html'
    email_template_name = 'users/password_reset_email.html'
    html_email_template_name = 'users/password_reset_email.html'
    success_url = reverse_lazy('users:password_reset_done')
    success_message = "An email with instructions to reset your password has been sent to %(email)s."
    subject_template_name = 'users/password_reset_subject.txt'


def logout_view(request):
    logout(request)
    return redirect(to='quotes:root')

users/templates/users/login.html
{% extends 'helper/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Login User</h2>

    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <span {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</span>
        {% endfor %}
    </div>
    {% endif %}

    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}

    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>

        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password }}
            </label>
            <span>{{form.errors.password}}</span>
        </div>
        <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
        </div>
         <div class="small text-center">
        <a href="{% url 'users:password_reset' %}" class="text-center"><i>Forgot Password?</i></a>
    </div>
    </form>
</div>
{% endblock %}

users/templates/users/logout.html
{% extends 'helper/base.html' %}

{% block content %}

    <div class="container mt-3">
        <h1>Return please!</h1>
    </div>

{% endblock %}

users/templates/users/password_reset.html
{% extends "helper/base.html" %}

{% block content %}

<h2>Password reset</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Request password reset</button>
</form>

{% endblock %}

users/templates/users/password_reset_complete.html
{% extends "helper/base.html" %}

{% block content %}

    <h2>Password reset complete!</h2>

{% endblock %}

users/templates/users/password_reset_confirm.html
{% extends "helper/base.html" %}

{% block content %}

<h2>Enter new password</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save new password</button>
</form>

{% endblock %}

users/templates/users/password_reset_done.html
{% extends "helper/base.html" %}

{% block content %}

<h2>Password reset request sent</h2>
<p>We've emailed you with instructions on how to reset your password.</p>

{% endblock %}

users/templates/users/password_reset_email.html
{% autoescape off %}
<body>
<p>Hi {{ user.username }},</p>
<p>You requested a password reset for your account. Please follow this link to set a new password:</p>
<p>
    <a href="{{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">
        {{ protocol }}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}
    </a>
</p>
<p>If you didn't request a password reset, please ignore this email.</p>
<p>Thanks,</p>
<p>The Our Team</p>
{% endautoescape %}

users/templates/users/register.html
{% extends 'helper/base.html' %}

{% block content %}
<div class="container mt-3">
    <h2>Register User</h2>
    {% if form.errors and form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
        {{form.non_field_errors}}
    </div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <div class="mb-3">
            <label class="form-label">Username
                {{ form.username }}
            </label>
            <span>{{form.errors.username}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Email
                {{ form.email }}
            </label>
            <span>{{form.errors.email}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Password
                {{ form.password1 }}
            </label>
            <span>{{form.errors.password1}}</span>
        </div>
        <div class="mb-3">
            <label class="form-label">Repeat Password
                {{ form.password2 }}
            </label>
            <span>{{form.errors.password2}}</span>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
        <button type="reset" class="btn btn-secondary">Reset</button>
    </form>
</div>
{% endblock %}