contacts/urls.py
from django.urls import path, include
from . import views

app_name = 'contacts'

urlpatterns = [
    path('', views.contact_list, name='contact_list'),
    path('add_contact/', views.add_contact, name='add_contact'),
    path('edit_contact/<int:pk>/', views.edit_contact, name='edit_contact'),
    path('delete_contact/<int:pk>/', views.delete_contact, name='delete_contact'),
    path('upcoming_birthdays_list/', views.upcoming_birthdays_list, name='upcoming_birthdays_list'),
]

files/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'files'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('upload/', views.upload_file, name='upload_file'),
    path('files/', views.file_list, name='file_list'),
    path('delete/<str:file_id>/', views.delete_file, name='delete_file')
]

helper/urls.py
from django.urls import path
from . import views

app_name = 'quotes'
urlpatterns = [
    path('', views.main, name='root'),
    #path('admin/', views.main, name='root')
]

interactive_helper/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("helper.urls")),
    path("files/", include("files.urls")),
    path("users/", include("users.urls")),
    path('contacts/', include("contacts.urls")),
    path('notes/', include("notes.urls"))
]

notes/urls.py
from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    path('', views.main, name='index'),
    path('add_notes/', views.note, name='add_notes'),
    path('tag/', views.tag, name='tag'),
    path('detail/<int:note_id>', views.detail, name='detail'),
    path('done/<int:note_id>', views.set_done, name='set_done'),
    path('edit_note/<int:pk>/', views.edit_note, name='edit'),
    path('delete/<int:note_id>', views.delete_note, name='delete'),
    path('tag/<int:tag_id>/delete/', views.delete_tag, name='delete_tag'),
]

users/urls.py
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView

from .import views
from .forms import LoginForm, RegisterForm

app_name = 'users'

urlpatterns =[
    path('signup/', views.RegisterView.as_view(template_name='users/register.html', form_class=RegisterForm), name='signup'),
    path('login/', LoginView.as_view(template_name='users/login.html', form_class=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url='/users/reset-password/complete/'),
            name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete')
    ]

helper/models.py
from django.db import models

# Create your models here.

helper/views.py
# views.py
from django.shortcuts import render
from django.http import HttpResponse
from .news import parse_news  # імпортуємо функцію parse_news з news.py
import requests

def main(request):
    url = 'https://dev.ua/news'

    # Отримуємо HTML вміст сторінки
    response = requests.get(url)
    if response.status_code != 200:
        return HttpResponse(f'Failed to retrieve the webpage. Status code: {response.status_code}')

    html_content = response.text

    # Викликаємо функцію parse_news з вхідним HTML-контентом і отримуємо результат
    parsed_news = parse_news(html_content)

    if parsed_news:
        context = {
            'news_list': parsed_news
        }
        return render(request, 'helper/index.html', context)
    else:
        return HttpResponse('Failed to parse news.')





    #return render(request, "helper/index.html")

helper/templates/helper/base copy.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'helper/style.css' %}">
    <title>Homework</title>
</head>
<body>

    <div class="container">
        <div class="row header-box pt-3 mb-3">
            <div class="col-md-8">
                <h1>
                    <a href="/" style="text-decoration: none">Interactive helper</a>
                </h1>
            </div>
            <div class="col-md-4">
                <p>
                    {% if user.is_authenticated %}
                    <a href="{% url 'contact_list' %}" class="btn btn-primary">Contacts</a>
                    <a href="#" class="btn btn-primary">Notes</a>
                    <a href="{% url 'files:file_list' %}" class="btn btn-primary">Files</a>
                    <a href="{% url 'files:upload_file' %}" class="btn btn-primary">Upload</a>
                    <a href="{% url 'users:logout' %}" class="btn btn-primary">Logout</a>

                    {% else %}
                    <a href="{% url 'users:signup' %}" class="btn btn-primary">SignUp</a>
                    <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                    {% endif %}

                </p>
            </div>
        </div>


    {% block content %} {% endblock %}

    </div>
    <footer class="footer">
        <div class="container">

        </div>
    </footer>


</body>
</html>

helper/templates/helper/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Interactive helper</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'helper/style.css' %}">
</head>
<body>

<div class="container text-bg-light p-3">
    <div class="row g-3">
        <div class="col-auto">
            <h1>
                <a href="/" style="text-decoration: none">Персональний помічник</a>
            </h1>
        </div>
        <div class="col-auto " style="padding-top:10px">
            <p>
                {% if user.is_authenticated %}
                <a href="{% url 'contacts:contact_list' %}" class="btn btn-primary">Контакти</a>
                <a href="{% url 'notes:index' %}" class="btn btn-primary">Нотатки</a>
                <a href="{% url 'files:file_list' %}" class="btn btn-primary">Файли</a>
                <a href="{% url 'files:upload_file' %}" class="btn btn-primary">Завантажити</a>
                <a href="{% url 'users:logout' %}" class="btn btn-primary">Вийти</a>
                {% else %}
                <a href="{% url 'users:signup' %}" class="btn btn-primary">Реєстрація</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Ввійти</a>
                {% endif %}
            </p>
        </div>
    </div>

    <div class="content">
        {% block content %}{% endblock %}
    </div>

</div>

<footer class="footer">
    <div class="container">

    </div>
</footer>

</body>
</html>

helper/templates/helper/index.html
{% extends 'helper/base.html' %}

{% block content %}

<div class="row">
    <h2>Новини</h2>

    {% if news_list %}
        {% for news in news_list %}
            <div class="card mb-3">
                <div class="row g-0">
                    <div class="col-md-3">
                        <img src="{{ news.img_url }}" alt="{{ news.title }}" style="width: 100%;  height: auto;">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ news.title }}</h5>
                            <p class="card-text">{{ news.description }}</p>
                            <a href="{{ news.news_link }}" class="btn btn-primary">Детальніше</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p>Немає новин для відображення.</p>
    {% endif %}

</div>

{% endblock %}